on:
  workflow_dispatch:

name: Scrape-Fillers
jobs:
  Scrape-Fillers:
    name: Scrape-Fillers
    runs-on: ubuntu-latest
    steps:
      # ...
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      # run any `bun` or `bunx` command
      - run: cd OnePiece-Filler && bun install cheerio && bun ScrapeFillers.ts

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: my-artifact
          path: ./OnePiece-Filler/one-piece.js

      - name: Get today's date
        id: date
        run: echo "date=$(date +'%d.%m.%Y')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "OnePieceFiller"
          name: "One Piece Filler ${{ steps.date.outputs.date }}"
          files: |
            ./OnePiece-Filler/one-piece.js
    
